# -*- coding: utf-8 -*-
# data.py

# ********** Present Tense ************
present_tense = [
[u'hablar', u'to speak; talk', u'hablo', u'hablas', u'habla', u'hablamos', u'habláis', u'hablan'],
[u'comer', u'to eat; feed', u'como', u'comes', u'come', u'comemos', u'coméis', u'comen'],
[u'escrebir', u'to write', u'escrebo', u'escrebes', u'escrebe', u'escrebimos', u'escrebís', u'escreben'],
[u'pagar', u'to pay', u'pago', u'pagas', u'paga', u'pagamos', u'pagáis', u'pagan'],
[u'tocar', u'to touch; play an instrument', u'toco', u'tocas', u'toca', u'tocamos', u'tocáis', u'tocan'],
[u'almorzar', u'to (have) lunch', u'almuerzo', u'almuerzas', u'almuerza', u'almorzamos', u'almorzáis', u'almuerzan'],
[u'caer', u'to fall; drop', u'caigo', u'caes', u'cae', u'caemos', u'caéis', u'caen'],
[u'cerrar', u'to close; shut', u'cierro', u'cierras', u'cierra', u'cerramos', u'cerráis', u'cierran'],
[u'comenzar', u'to begin; start', u'comienzo', u'comienzas', u'comienza', u'comenzamos', u'comenzáis', u'comienzan'],
[u'conocer', u'to be familiar', u'conozco', u'conoces', u'conoce', u'conocemos', u'conocéis', u'conocen'],
[u'conseguir', u'to get', u'consigo', u'consigues', u'consigue', u'conseguimos', u'conseguís', u'consiguen'],
[u'contar', u'to count; tell', u'cuento', u'cuentas', u'cuenta', u'contamos', u'contáis', u'cuentan'],
[u'dar', u'to give', u'doy', u'das', u'da', u'damos', u'dais', u'dan'],
[u'decir', u'to say; tell', u'digo', u'dices', u'dice', u'decimos', u'decís', u'dicen'],
[u'defender', u'to defend', u'defiendo', u'defiendes', u'defiende', u'defendemos', u'defendéis', u'defienden'],
[u'dormir', u'to sleep', u'duermo', u'duermes', u'duerme', u'dormimos', u'dormís', u'duermen'],
[u'empezar', u'to begin; start', u'empiezo', u'empiezas', u'empieza', u'empezamos', u'empezáis', u'empiezan'],
[u'encontrar', u'to find; meet', u'encuentro', u'encuentras', u'encuentra', u'encontramos', u'encontráis', u'encuentran'],
[u'entender', u'to understand', u'entiendo', u'entiendes', u'entiende', u'entendemos', u'entendéis', u'entienden'],
[u'estar', u'to be (temporary)', u'estoy', u'estás', u'está', u'estamos', u'estáis', u'están'],
[u'haber', u'to have; to credit', u'he', u'has', u'ha', u'hemos', u'habéis', u'han'],
[u'hacer', u'to do; make; perform', u'hago', u'haces', u'hace', u'hacemos', u'hacéis', u'hacen'],
[u'ir', u'to go', u'voy', u'vas', u'va', u'vamos', u'vais', u'van'],
[u'jugar', u'to play', u'juego', u'juegas', u'juega', u'jugamos', u'jugáis', u'juegan'],
[u'llover', u'to rain', u'lluevo', u'llueves', u'llueve', u'llovemos', u'llovéis', u'llueven'],
[u'mostrar', u'to show', u'muestro', u'muestras', u'muestra', u'mostramos', u'mostráis', u'muestran'],
[u'mover', u'to move', u'muevo', u'mueves', u'mueve', u'movemos', u'movéis', u'mueven'],
[u'nevar', u'to snow', u'nievo', u'nievas', u'nieva', u'nevamos', u'neváis', u'nievan'],
[u'oir', u'to hear', u'oigo', u'oyes', u'oye', u'oímos', u'oís', u'oyen'],
[u'pedir', u'to book; order; ask; reserve', u'pido', u'pides', u'pide', u'pedimos', u'pedís', u'piden'],
[u'pensar', u'to think', u'pienso', u'piensas', u'piensa', u'pensamos', u'pensáis', u'piensan'],
[u'perder', u'to lose; miss', u'pierdo', u'pierdes', u'pierde', u'perdemos', u'perdéis', u'pierden'],
[u'poder', u'to be able; can; may', u'puedo', u'puedes', u'puede', u'podemos', u'podéis', u'pueden'],
[u'poner', u'to put; put on; lay; send', u'pongo', u'pones', u'pone', u'ponemos', u'ponéis', u'ponen'],
[u'querer', u'to want; wish; like', u'quiero', u'quieres', u'quiere', u'queremos', u'queréis', u'quieren'],
[u'recordar', u'to remember; remind', u'recuerdo', u'recuerdas', u'recuerda', u'recordamos', u'recordáis', u'recuerdan'],
[u'repetir', u'to repeat', u'repito', u'repites', u'repite', u'repetimos', u'repetís', u'repiten'],
[u'saber', u'to know; know how', u'sé', u'sabes', u'sabe', u'sabemos', u'sabéis', u'saben'],
[u'salir', u'to exit; leave', u'salgo', u'sales', u'sale', u'salimos', u'salís', u'salen'],
[u'seguir', u'to follow', u'sigo', u'sigues', u'sigue', u'seguimos', u'seguís', u'siguen'],
[u'sentir', u'to feel', u'siento', u'sientes', u'siente', u'sentimos', u'sentís', u'sienten'],
[u'ser', u'to be (descriptive)', u'soy', u'eres', u'es', u'somos', u'sois', u'son'],
[u'servir', u'to serve', u'sirvo', u'sirves', u'sirve', u'servimos', u'servís', u'sirven'],
[u'tener', u'to have; own; keep', u'tengo', u'tienes', u'tiene', u'tenemos', u'tenéis', u'tienen'],
[u'traer', u'to bring; fetch', u'traigo', u'traes', u'trae', u'traemos', u'traéis', u'traen'],
[u'venir', u'to come', u'vengo', u'vienes', u'viene', u'venimos', u'venís', u'vienen'],
[u'ver', u'to see; view; look; consider', u'veo', u'ves', u've', u'vemos', u'véis', u'ven'],
[u'volar', u'to fly', u'vuelo', u'vuelas', u'vuela', u'volamos', u'voláis', u'vuelan'],
[u'volver', u'to return; go back', u'vuelvo', u'vuelves', u'vuelve', u'volvemos', u'volvéis', u'vuelven']
]

# ********** Preterit Tense ************
preterit_tense = [
[u'hablar', u'to speak; talk', u'hablé', u'hablaste', u'habló', u'hablamos', u'hablasteis', u'hablaron'],
[u'comer', u'to eat; feed', u'comí', u'comiste', u'comió', u'comimos', u'comisteis', u'comieron'],
[u'escrebir', u'to write', u'escrebí', u'escrebiste', u'escrebió', u'escrebimos', u'escrebisteis', u'escrebieron'],
[u'pagar', u'to pay', u'pagué', u'pagaste', u'pagó', u'pagamos', u'pagasteis', u'pagaron'],
[u'tocar', u'to touch; play an instrument', u'toqué', u'tocaste', u'tocó', u'tocamos', u'tocasteis', u'tocaron'],
[u'almorzar', u'to (have) lunch', u'almorcé', u'almorzaste', u'almorzó', u'almorzamos', u'almorzasteis', u'almorzaron'],
[u'caer', u'to fall; drop', u'caí', u'caíste', u'cayó', u'caímos', u'caísteis', u'cayeron'],
[u'cerrar', u'to close; shut', u'cerré', u'cerraste', u'cerró', u'cerramos', u'cerrasteis', u'cerraron'],
[u'comenzar', u'to begin; start', u'comencé', u'comenzaste', u'comenzó', u'comenzamos', u'comenzasteis', u'comenzaron'],
[u'conocer', u'to be familiar', u'conocí', u'conociste', u'conoció', u'conocimos', u'conocisteis', u'conocieron'],
[u'conseguir', u'to get', u'conseguí', u'conseguiste', u'consiguió', u'conseguimos', u'conseguisteis', u'consiguieron'],
[u'contar', u'to count; tell', u'conté', u'contaste', u'contó', u'contamos', u'contasteis', u'contaron'],
[u'dar', u'to give', u'di', u'diste', u'dio', u'dimos', u'disteis', u'dieron'],
[u'decir', u'to say; tell', u'dije', u'dijiste', u'dijo', u'dijimos', u'dijisteis', u'dijeron'],
[u'defender', u'to defend', u'defendí', u'defendiste', u'defendió', u'defendimos', u'defendisteis', u'defendieron'],
[u'dormir', u'to sleep', u'dormí', u'dormiste', u'durmío', u'dormimos', u'dormisteis', u'durmieron'],
[u'empezar', u'to begin; start', u'empecé', u'empezaste', u'empezó', u'empezamos', u'empezasteis', u'empezaron'],
[u'encontrar', u'to find; meet', u'encontré', u'encontraste', u'encontró', u'encontramos', u'encontrasteis', u'encontraron'],
[u'entender', u'to understand', u'entendí', u'entendiste', u'entendió', u'entendimos', u'entendisteis', u'entendieron'],
[u'estar', u'to be (temporary)', u'estuve', u'estuviste', u'estuvo', u'estuvimos', u'estuvisteis', u'estuvieron'],
[u'haber', u'to have; to credit', u'hube', u'hubiste', u'hubo', u'hubimos', u'hubisteis', u'hubieron'],
[u'hacer', u'to do; make; perform', u'hice', u'hiciste', u'hizo', u'hicimos', u'hicisteis', u'hicieron'],
[u'ir', u'to go', u'fui', u'fuiste', u'fue', u'fuimos', u'fuisteis', u'fueron'],
[u'jugar', u'to play', u'jugué', u'jugaste', u'jugó', u'jugamos', u'jugasteis', u'jugaron'],
[u'llover', u'to rain', u'lloví', u'lloviste', u'llovió', u'llovimos', u'llovisteis', u'llovieron'],
[u'mostrar', u'to show', u'mostré', u'mostraste', u'mostró', u'mostramos', u'mostrasteis', u'mostraron'],
[u'mover', u'to move', u'moví', u'moviste', u'movió', u'movimos', u'movisteis', u'movieron'],
[u'nevar', u'to snow', u'nevé', u'nevaste', u'nevó', u'nevamos', u'nevasteis', u'nevaron'],
[u'oir', u'to hear', u'oí', u'oíste', u'oyó', u'oímos', u'oísteis', u'oyeron'],
[u'pedir', u'to book; order; ask; reserve', u'pedí', u'pediste', u'pidió', u'pedimos', u'pedisteis', u'pidieron'],
[u'pensar', u'to think', u'pensé', u'pensaste', u'pensó', u'pensamos', u'pensasteis', u'pensaron'],
[u'perder', u'to lose; miss', u'perdí', u'perdiste', u'perdió', u'perdimos', u'perdisteis', u'perdieron'],
[u'poder', u'to be able; can; may', u'pude', u'pudiste', u'pudo', u'pudimos', u'pudisteis', u'pudieron'],
[u'poner', u'to put; put on; lay; send', u'puse', u'pusiste', u'puso', u'pusimos', u'pusisteis', u'pusieron'],
[u'querer', u'to want; wish; like', u'quise', u'quisiste', u'quiso', u'quisimos', u'quisisteis', u'quisieron'],
[u'recordar', u'to remember; remind', u'recordé', u'recordaste', u'recordó', u'recordamos', u'recordasteis', u'recordaron'],
[u'repetir', u'to repeat', u'repetí', u'repetiste', u'repitió', u'repetimos', u'repetisteis', u'repitieron'],
[u'saber', u'to know; know how', u'supe', u'supiste', u'supo', u'supimos', u'supisteis', u'supieron'],
[u'salir', u'to exit; leave', u'salí', u'saliste', u'salió', u'salimos', u'salisteis', u'salieron'],
[u'seguir', u'to follow', u'seguí', u'seguiste', u'siguió', u'seguimos', u'seguisteis', u'siguieron'],
[u'sentir', u'to feel', u'sentí', u'sentiste', u'sintió', u'sentimos', u'sentisteis', u'sintieron'],
[u'ser', u'to be (descriptive)', u'fui', u'fuiste', u'fue', u'fuimos', u'fuisteis', u'fueron'],
[u'servir', u'to serve', u'serví', u'serviste', u'sirvió', u'servimos', u'servisteis', u'sirvieron'],
[u'tener', u'to have; own; keep', u'tuve', u'tuviste', u'tuvo', u'tuvimos', u'tuvisteis', u'tuvieron'],
[u'traer', u'to bring; fetch', u'traje', u'trajiste', u'trajo', u'trajimos', u'trajisteis', u'trajeron'],
[u'venir', u'to come', u'vine', u'viniste', u'vinó', u'vinimos', u'vininsteis', u'vinieron'],
[u'ver', u'to see; view; look; consider', u'ví', u'viste', u'vió', u'vimos', u'visteis', u'vieron'],
[u'volar', u'to fly', u'volé', u'volaste', u'voló', u'volamos', u'volasteis', u'volaron'],
[u'volver', u'to return; go back', u'volví', u'volviste', u'volvió', u'volvimos', u'volvisteis', u'volvieron']
]

# ********** Imperfect Tense ************
imperfect_tense = [
[u'hablar', u'to speak; talk', u'hablaba', u'hablabas', u'hablaba', u'hablábamos', u'hablabais', u'hablaban'],
[u'comer', u'to eat; feed', u'comía', u'comías', u'comía', u'comíamos', u'comíais', u'comían'],
[u'escrebir', u'to write', u'escrebía', u'escrebías', u'escrebía', u'escrebíamos', u'escrebíais', u'escrebían'],
[u'pagar', u'to pay', u'pagaba', u'pagabas', u'pagaba', u'pagábamos', u'pagabais', u'pagaban'],
[u'tocar', u'to touch; play an instrument', u'tocaba', u'tocabas', u'tocaba', u'tocábamos', u'tocabais', u'tocaban'],
[u'almorzar', u'to (have) lunch', u'almorzaba', u'almorzabas', u'almorzaba', u'almorzábamos', u'almorzabais', u'almorzaban'],
[u'caer', u'to fall; drop', u'caía', u'caías', u'caía', u'caíamos', u'caíais', u'caían'],
[u'cerrar', u'to close; shut', u'cerraba', u'cerrabas', u'cerraba', u'cerrábamos', u'cerrabais', u'cerraban'],
[u'comenzar', u'to begin; start', u'comenzaba', u'comenzabas', u'comenzaba', u'comenzábamos', u'comenzabais', u'comenzaban'],
[u'conocer', u'to be familiar', u'conocía', u'conocías', u'conocía', u'conocíamos', u'conocíais', u'conocían'],
[u'conseguir', u'to get', u'conseguía', u'conseguías', u'conseguía', u'conseguíamos', u'conseguíais', u'conseguían'],
[u'contar', u'to count; tell', u'contaba', u'contabas', u'contaba', u'contábamos', u'contabais', u'contaban'],
[u'dar', u'to give', u'daba', u'dabas', u'daba', u'dábamos', u'dabais', u'daban'],
[u'decir', u'to say; tell', u'decía', u'decías', u'decía', u'decíamos', u'decíais', u'decían'],
[u'defender', u'to defend', u'defendía', u'defendías', u'defendía', u'defendíamos', u'defendíais', u'defendían'],
[u'dormir', u'to sleep', u'dormía', u'dormías', u'dormía', u'dormíamos', u'dormíais', u'dormían'],
[u'empezar', u'to begin; start', u'empezaba', u'empezabas', u'empezaba', u'empezábamos', u'empezabais', u'empezaban'],
[u'encontrar', u'to find; meet', u'encontraba', u'encontrabas', u'encontraba', u'encontrábamos', u'encontrabais', u'encontraban'],
[u'entender', u'to understand', u'entendía', u'entendías', u'entendía', u'entendíamos', u'entendíais', u'entendían'],
[u'estar', u'to be (temporary)', u'estaba', u'estabas', u'estaba', u'estábamos', u'estabais', u'estaban'],
[u'haber', u'to have; to credit', u'había', u'habías', u'había', u'habíamos', u'habíais', u'habían'],
[u'hacer', u'to do; make; perform', u'hacía', u'hacías', u'hacía', u'hacíamos', u'hacíais', u'hacían'],
[u'ir', u'to go', u'iba', u'ibas', u'iba', u'íbamos', u'ibais', u'iban'],
[u'jugar', u'to play', u'jugaba', u'jugabas', u'jugaba', u'jugábamos', u'jugabais', u'jugaban'],
[u'llover', u'to rain', u'llovía', u'llovías', u'llovía', u'llovíamos', u'llovíais', u'llovían'],
[u'mostrar', u'to show', u'mostraba', u'mostrabas', u'mostraba', u'mostrábamos', u'mostrabais', u'mostraban'],
[u'mover', u'to move', u'movía', u'movías', u'movía', u'movíamos', u'movíais', u'movían'],
[u'nevar', u'to snow', u'nevaba', u'nevabas', u'nevaba', u'nevábamos', u'nevabais', u'nevaban'],
[u'oir', u'to hear', u'oía', u'oías', u'oía', u'oíamos', u'oíais', u'oían'],
[u'pedir', u'to book; order; ask; reserve', u'pedía', u'pedías', u'pedía', u'pedíamos', u'pedíais', u'pedían'],
[u'pensar', u'to think', u'pensaba', u'pensabas', u'pensaba', u'pensábamos', u'pensabais', u'pensaban'],
[u'perder', u'to lose; miss', u'perdía', u'perdías', u'perdía', u'perdíamos', u'perdíais', u'perdían'],
[u'poder', u'to be able; can; may', u'podía', u'podías', u'podía', u'podíamos', u'podíais', u'podían'],
[u'poner', u'to put; put on; lay; send', u'ponía', u'ponías', u'ponía', u'poníamos', u'poníais', u'ponían'],
[u'querer', u'to want; wish; like', u'quería', u'querías', u'quería', u'queríamos', u'queríais', u'querían'],
[u'recordar', u'to remember; remind', u'recordaba', u'recordabas', u'recordaba', u'recordábamos', u'recordabais', u'recordaban'],
[u'repetir', u'to repeat', u'repetía', u'repetías', u'repetía', u'repetíamos', u'repetíais', u'repetían'],
[u'saber', u'to know; know how', u'sabía', u'sabías', u'sabía', u'sabíamos', u'sabíais', u'sabían'],
[u'salir', u'to exit; leave', u'salía', u'salías', u'salía', u'salíamos', u'salíais', u'salían'],
[u'seguir', u'to follow', u'seguía', u'seguías', u'seguía', u'seguíamos', u'seguíais', u'seguían'],
[u'sentir', u'to feel', u'sentía', u'sentías', u'sentía', u'sentíamos', u'sentíais', u'sentían'],
[u'ser', u'to be (descriptive)', u'era', u'eras', u'era', u'éramos', u'erais', u'eran'],
[u'servir', u'to serve', u'servía', u'servías', u'servía', u'servíamos', u'servíais', u'servían'],
[u'tener', u'to have; own; keep', u'tenía', u'tenías', u'tenía', u'teníamos', u'teníais', u'tenían'],
[u'traer', u'to bring; fetch', u'traía', u'traías', u'traía', u'traíamos', u'traíais', u'traían'],
[u'venir', u'to come', u'venía', u'venías', u'venía', u'veníamos', u'veníais', u'venían'],
[u'ver', u'to see; view; look; consider', u'veía', u'veías', u'veía', u'veíamos', u'veíais', u'veían'],
[u'volar', u'to fly', u'volaba', u'volabas', u'volaba', u'volábamos', u'volabais', u'volaban'],
[u'volver', u'to return; go back', u'volvía', u'volvías', u'volvía', u'volvíamos', u'volvíais', u'volvían']
]

# ********** Future Tense ************
future_tense = [
[u'hablar', u'to speak; talk', u'hablaré', u'hablarás', u'hablará', u'hablaremos', u'hablaréis', u'hablarán'],
[u'comer', u'to eat; feed', u'comeré', u'comerás', u'comerá', u'comeremos', u'comeréis', u'comerán'],
[u'escrebir', u'to write', u'escrebiré', u'escrebirás', u'escrebirá', u'escrebiremos', u'escrebiréis', u'escrebirán'],
[u'pagar', u'to pay', u'pagaré', u'pagarás', u'pagará', u'pagaremos', u'pagaréis', u'pagarán'],
[u'tocar', u'to touch; play an instrument', u'tocaré', u'tocarás', u'tocará', u'tocaremos', u'tocaréis', u'tocarán'],
[u'almorzar', u'to (have) lunch', u'almorzaré', u'almorzarás', u'almorzará', u'almorzaremos', u'almorzaréis', u'almorzarán'],
[u'caer', u'to fall; drop', u'caeré', u'caerás', u'caerá', u'caeremos', u'caeréis', u'caerán'],
[u'cerrar', u'to close; shut', u'cerraré', u'cerrarás', u'cerrará', u'cerraremos', u'cerraréis', u'cerrarán'],
[u'comenzar', u'to begin; start', u'comenzaré', u'comenzarás', u'comenzará', u'comenzaremos', u'comenzaréis', u'comenzarán'],
[u'conocer', u'to be familiar', u'conoceré', u'conocerás', u'conocerá', u'conoceremos', u'conoceréis', u'conocerán'],
[u'conseguir', u'to get', u'consiguiere', u'consiguieres', u'consiguiere', u'consiguiéremos', u'consiguiereis', u'consiguieren'],
[u'contar', u'to count; tell', u'contaré', u'contarás', u'contará', u'contaremos', u'contaréis', u'contarán'],
[u'dar', u'to give', u'daré', u'darás', u'dará', u'daremos', u'daréis', u'darán'],
[u'decir', u'to say; tell', u'diré', u'dirás', u'dirá', u'diremos', u'diréis', u'dirán'],
[u'defender', u'to defend', u'defenderé', u'defenderás', u'defenderá', u'defenderemos', u'defenderéis', u'defenderán'],
[u'dormir', u'to sleep', u'dormiré', u'dormirás', u'dormirá', u'dormiremos', u'dormiréis', u'dormirán'],
[u'empezar', u'to begin; start', u'empezaré', u'empezarás', u'empezará', u'empezaremos', u'empezaréis', u'empezarán'],
[u'encontrar', u'to find; meet', u'encontraré', u'encontrarás', u'encontrará', u'encontraremos', u'encontraréis', u'encontrarán'],
[u'entender', u'to understand', u'entenderé', u'entenderás', u'entenderá', u'entenderemos', u'entenderéis', u'entenderán'],
[u'estar', u'to be (temporary)', u'estaré', u'estarás', u'estará', u'estaremos', u'estaréis', u'estarán'],
[u'haber', u'to have; to credit', u'habré', u'habrás', u'habrá', u'habremos', u'habréis', u'habrán'],
[u'hacer', u'to do; make; perform', u'haré', u'harás', u'hará', u'haremos', u'haréis', u'harán'],
[u'ir', u'to go', u'iré', u'irás', u'irá', u'iremos', u'iréis', u'irán'],
[u'jugar', u'to play', u'jugaré', u'jugarás', u'jugará', u'jugaremos', u'jugaréis', u'jugarán'],
[u'llover', u'to rain', u'lloveré', u'lloverás', u'lloverá', u'lloveremos', u'lloveréis', u'lloverán'],
[u'mostrar', u'to show', u'mostraré', u'mostrarás', u'mostrará', u'mostraremos', u'mostraréis', u'mostrarán'],
[u'mover', u'to move', u'moveré', u'moverás', u'moverá', u'moveremos', u'moveréis', u'moverán'],
[u'nevar', u'to snow', u'nevaré', u'nevarás', u'nevará', u'nevaremos', u'nevaréis', u'nevarán'],
[u'oir', u'to hear', u'oiré', u'oirás', u'oirá', u'oiremos', u'oiréis', u'oirán'],
[u'pedir', u'to book; order; ask; reserve', u'pediré', u'pedirás', u'pedirá', u'pediremos', u'pediréis', u'pedirán'],
[u'pensar', u'to think', u'pensaré', u'pensarás', u'pensará', u'pensaremos', u'pensaréis', u'pensarán'],
[u'perder', u'to lose; miss', u'perderé', u'perderás', u'perderá', u'perderemos', u'perderéis', u'perderán'],
[u'poder', u'to be able; can; may', u'podré', u'podrás', u'podrá', u'podremos', u'podréis', u'podrán'],
[u'poner', u'to put; put on; lay; send', u'pondré', u'pondrás', u'pondrá', u'pondremos', u'pondréis', u'pondrán'],
[u'querer', u'to want; wish; like', u'querré', u'querrás', u'querrá', u'querremos', u'querréis', u'querrán'],
[u'recordar', u'to remember; remind', u'recordaré', u'recordarás', u'recordará', u'recordaremos', u'recordaréis', u'recordarán'],
[u'repetir', u'to repeat', u'repetiré', u'repetirás', u'repetirá', u'repetiremos', u'repetiréis', u'repetirán'],
[u'saber', u'to know; know how', u'sabré', u'sabrás', u'sabrá', u'sabremos', u'sabréis', u'sabrán'],
[u'salir', u'to exit; leave', u'saldré', u'saldrás', u'saldrá', u'saldremos', u'saldréis', u'saldrán'],
[u'seguir', u'to follow', u'seguiré', u'seguirás', u'seguirá', u'seguiremos', u'seguiréis', u'seguirán'],
[u'sentir', u'to feel', u'sentiré', u'sentirás', u'sentirá', u'sentiremos', u'sentiréis', u'sentirán'],
[u'ser', u'to be (descriptive)', u'seré', u'serás', u'será', u'seremos', u'seréis', u'serán'],
[u'servir', u'to serve', u'serviré', u'servirás', u'servirá', u'serviremos', u'serviréis', u'servirán'],
[u'tener', u'to have; own; keep', u'tendré', u'tendrás', u'tendrá', u'tendremos', u'tendréis', u'tendrán'],
[u'traer', u'to bring; fetch', u'traeré', u'traerás', u'traerá', u'traeremos', u'traeréis', u'traerán'],
[u'venir', u'to come', u'vendré', u'vendrás', u'vendrá', u'vendremos', u'vendréis', u'vendrán'],
[u'ver', u'to see; view; look; consider', u'veré', u'verás', u'verá', u'veremos', u'veréis', u'verán'],
[u'volar', u'to fly', u'volaré', u'volarás', u'volará', u'volaremos', u'volaréis', u'volarán'],
[u'volver', u'to return; go back', u'volveré', u'volverás', u'volverá', u'volveremos', u'volveréis', u'volverán']
]

# ********** Present Subjuncive Tense ************
present_subjunctive_tense = [
[u'hablar', u'to speak; talk', u'hable', u'hables', u'hable', u'hablemos', u'habléis', u'hablen'],
[u'comer', u'to eat; feed', u'coma', u'comas', u'coma', u'comamos', u'comáis', u'coman'],
[u'escrebir', u'to write', u'escreba', u'escrebas', u'escreba', u'escrebamos', u'escrebáis', u'escreban'],
[u'pagar', u'to pay', u'pague', u'pagues', u'pague', u'paguemos', u'paguéis', u'paguen'],
[u'tocar', u'to touch; play an instrument', u'toque', u'toques', u'toque', u'toquemos', u'toquéis', u'toquen'],
[u'almorzar', u'to (have) lunch', u'almuerce', u'almuerces', u'almuerce', u'almorcemos', u'almorcéis', u'almuercen'],
[u'caer', u'to fall; drop', u'caiga', u'caigas', u'caiga', u'caigamos', u'caigáis', u'caigan'],
[u'cerrar', u'to close; shut', u'cierre', u'cierres', u'cierre', u'cerremos', u'cerréis', u'cierren'],
[u'comenzar', u'to begin; start', u'comience', u'comiences', u'comience', u'comencemos', u'comencéis', u'comiencen'],
[u'conocer', u'to be familiar', u'conozca', u'conozcas', u'conozca', u'conozcamos', u'conozcáis', u'conozcan'],
[u'conseguir', u'to get', u'consiga', u'consigas', u'consiga', u'consigamos', u'consigáis', u'consigan'],
[u'contar', u'to count; tell', u'cuente', u'cuentes', u'cuente', u'contemos', u'contéis', u'cuenten'],
[u'dar', u'to give', u'dé', u'des', u'dé', u'demos', u'deis', u'den'],
[u'decir', u'to say; tell', u'diga', u'digas', u'diga', u'digamos', u'digáis', u'digan'],
[u'defender', u'to defend', u'defienda', u'defiendas', u'defienda', u'defendamos', u'defendáis', u'defiendan'],
[u'dormir', u'to sleep', u'duerma', u'duermas', u'duerma', u'durmamos', u'durmáis', u'duerman'],
[u'empezar', u'to begin; start', u'empiece', u'empieces', u'empiece', u'empecemos', u'empecéis', u'empiecen'],
[u'encontrar', u'to find; meet', u'encuentre', u'encuentres', u'encuentre', u'encontremos', u'encontréis', u'encuentren'],
[u'entender', u'to understand', u'entienda', u'entiendas', u'entienda', u'entendamos', u'entendáis', u'entiendan'],
[u'estar', u'to be (temporary)', u'esté', u'estés', u'esté', u'estemos', u'estéis', u'estén'],
[u'haber', u'to have; to credit', u'haya', u'hayas', u'haya', u'hayamos', u'hayáis', u'hayan'],
[u'hacer', u'to do; make; perform', u'haga', u'hagas', u'haga', u'hagamos', u'hagáis', u'hagan'],
[u'ir', u'to go', u'vaya', u'vayas', u'vaya', u'vayamos', u'vayáis', u'vayan'],
[u'jugar', u'to play', u'juegue', u'juegues', u'juegue', u'jueguemos', u'jueguéis', u'jueguen'],
[u'llover', u'to rain', u'llueva', u'lluevas', u'llueva', u'llovamos', u'llováis', u'lluevan'],
[u'mostrar', u'to show', u'muestre', u'muestres', u'muestre', u'mostremos', u'mostréis', u'muestren'],
[u'mover', u'to move', u'mueva', u'muevas', u'mueva', u'movamos', u'mováis', u'muevan'],
[u'nevar', u'to snow', u'nieve', u'nieves', u'nieve', u'nevemos', u'nevéis', u'nieven'],
[u'oir', u'to hear', u'oiga', u'oigas', u'oiga', u'oigamos', u'oigáis', u'oigan'],
[u'pedir', u'to book; order; ask; reserve', u'pida', u'pidas', u'pida', u'pidamos', u'pidáis', u'pidan'],
[u'pensar', u'to think', u'piense', u'pienses', u'piense', u'pensemos', u'penséis', u'piensen'],
[u'perder', u'to lose; miss', u'pierda', u'pierdas', u'pierda', u'perdamos', u'perdáis', u'pierdan'],
[u'poder', u'to be able; can; may', u'pueda', u'puedas', u'pueda', u'podamos', u'podáis', u'puedan'],
[u'poner', u'to put; put on; lay; send', u'ponga', u'pongas', u'ponga', u'pongamos', u'pongáis', u'pongan'],
[u'querer', u'to want; wish; like', u'quiera', u'quieras', u'quiera', u'queramos', u'queráis', u'quieran'],
[u'recordar', u'to remember; remind', u'recuerde', u'recuerdes', u'recuerde', u'recordemos', u'recordéis', u'recuerden'],
[u'repetir', u'to repeat', u'repita', u'repitas', u'repita', u'repitamos', u'repitáis', u'repitan'],
[u'saber', u'to know; know how', u'sepa', u'sepas', u'sepa', u'sepamos', u'sepáis', u'sepan'],
[u'salir', u'to exit; leave', u'salga', u'salgas', u'salga', u'salgamos', u'salgáis', u'salgan'],
[u'seguir', u'to follow', u'siga', u'sigas', u'siga', u'sigamos', u'sigáis', u'sigan'],
[u'sentir', u'to feel', u'sienta', u'sientas', u'sienta', u'sientamos', u'sientáis', u'sientan'],
[u'ser', u'to be (descriptive)', u'sea', u'seas', u'sea', u'seamos', u'seáis', u'sean'],
[u'servir', u'to serve', u'sirva', u'sirvas', u'sirva', u'sirvamos', u'sirváis', u'sirvan'],
[u'tener', u'to have; own; keep', u'tenga', u'tengas', u'tenga', u'tengamos', u'tengáis', u'tengan'],
[u'traer', u'to bring; fetch', u'traiga', u'traigas', u'traiga', u'traigamos', u'traigáis', u'traigan'],
[u'venir', u'to come', u'venga', u'vengas', u'venga', u'vengamos', u'vengáis', u'vengan'],
[u'ver', u'to see; view; look; consider', u'vea', u'veas', u'vea', u'veamos', u'veáis', u'vean'],
[u'volar', u'to fly', u'vuele', u'vueles', u'vuele', u'volemos', u'voléis', u'vuelen'],
[u'volver', u'to return; go back', u'vuelva', u'vuelvas', u'vuelva', u'volvamos', u'volváis', u'vuelvan']
]

# ********** Imperfect Subjuncive Tense ************
imperfect_subjunctive_tense = [
[u'hablar', u'to speak; talk', u'hablara', u'hablaras', u'hablara', u'habláramos', u'hablarais', u'hablaran'],
[u'comer', u'to eat; feed', u'comiera', u'comieras', u'comiera', u'comiéramos', u'comierais', u'comieran'],
[u'escrebir', u'to write', u'escrebiera', u'escrebieras', u'escrebiera', u'escrebiéramos', u'escrebierais', u'escrebieran'],
[u'pagar', u'to pay', u'pagara', u'pagaras', u'pagara', u'pagáramos', u'pagarais', u'pagaran'],
[u'tocar', u'to touch; play an instrument', u'tocara', u'tocaras', u'tocara', u'tocáramos', u'tocarais', u'tocaran'],
[u'almorzar', u'to (have) lunch', u'almorzara', u'almorzaras', u'almorzara', u'almorzáramos', u'almorzarais', u'almorzaran'],
[u'caer', u'to fall; drop', u'cayera', u'cayeras', u'cayera', u'cayéramos', u'cayerais', u'cayeran'],
[u'cerrar', u'to close; shut', u'cerrara', u'cerraras', u'cerrara', u'cerráramos', u'cerrarais', u'cerraran'],
[u'comenzar', u'to begin; start', u'comenzara', u'comenzaras', u'comenzara', u'comenzáramos', u'comenzarais', u'comenzaran'],
[u'conocer', u'to be familiar', u'conociera', u'conocieras', u'conociera', u'conociéramos', u'conocierais', u'conocieran'],
[u'conseguir', u'to get', u'consiguiera', u'consiguieras', u'consiguiera', u'consiguiéramos', u'consiguierais', u'consiguieran'],
[u'contar', u'to count; tell', u'contara', u'contaras', u'contara', u'contáramos', u'contarais', u'contaran'],
[u'dar', u'to give', u'diera', u'dieras', u'diera', u'diéramos', u'dierais', u'dieran'],
[u'decir', u'to say; tell', u'dijera', u'dijeras', u'dijera', u'dijéramos', u'dijerais', u'dijeran'],
[u'defender', u'to defend', u'defendiera', u'defendieras', u'defendiera', u'defendiéramos', u'defendierais', u'defendieran'],
[u'dormir', u'to sleep', u'duermiera', u'duermieras', u'duermiera', u'duermiéramos', u'duermierais', u'durmieran'],
[u'empezar', u'to begin; start', u'empezara', u'empezaras', u'empezara', u'empezáramos', u'empezarais', u'empezaran'],
[u'encontrar', u'to find; meet', u'encontrara', u'encontraras', u'encontrara', u'encontráramos', u'encontrarais', u'encontraran'],
[u'entender', u'to understand', u'entendiera', u'entendieras', u'entendiera', u'entendiéramos', u'entendierais', u'entendieran'],
[u'estar', u'to be (temporary)', u'estuviera', u'estuvieras', u'estuviera', u'estuviéramos', u'estuvierais', u'estuvieran'],
[u'haber', u'to have; to credit', u'hubiera', u'hubieras', u'hubiera', u'hubiéramos', u'hubierais', u'hubieran'],
[u'hacer', u'to do; make; perform', u'hiciera', u'hicieras', u'hiciera', u'hiciéramos', u'hicierais', u'hicieran'],
[u'ir', u'to go', u'fuera', u'fueras', u'fuera', u'fuéramos', u'fuerais', u'fueran'],
[u'jugar', u'to play', u'jugara', u'jugaras', u'jugara', u'jugáramos', u'jugarais', u'jugaran'],
[u'llover', u'to rain', u'lloviera', u'llovieras', u'lloviera', u'lloviéramos', u'llovierais', u'llovieran'],
[u'mostrar', u'to show', u'mostrara', u'mostraras', u'mostrara', u'mostráramos', u'mostrarais', u'mostraran'],
[u'mover', u'to move', u'moviera', u'movieras', u'moviera', u'moviéramos', u'movierais', u'movieran'],
[u'nevar', u'to snow', u'nevara', u'nevaras', u'nevara', u'neváramos', u'nevarais', u'nevaran'],
[u'oir', u'to hear', u'oyera', u'oyeras', u'oyera', u'oyéramos', u'oyerais', u'oyeran'],
[u'pedir', u'to book; order; ask; reserve', u'pidiera', u'pidieras', u'pidiera', u'pidiéramos', u'pidierais', u'pidieran'],
[u'pensar', u'to think', u'pensara', u'pensaras', u'pensara', u'pensáramos', u'pensarais', u'pensaran'],
[u'perder', u'to lose; miss', u'perdiera', u'perdieras', u'perdiera', u'perdiéramos', u'perdierais', u'perdieran'],
[u'poder', u'to be able; can; may', u'pudiera', u'pudieras', u'pudiera', u'pudiéramos', u'pudierais', u'pudieran'],
[u'poner', u'to put; put on; lay; send', u'pusiera', u'pusieras', u'pusiera', u'pusiéramos', u'pusierais', u'pusieran'],
[u'querer', u'to want; wish; like', u'quisiera', u'quisieras', u'quisiera', u'quisiéramos', u'quisierais', u'quisieran'],
[u'recordar', u'to remember; remind', u'recordara', u'recordaras', u'recordara', u'recordáramos', u'recordarais', u'recordaran'],
[u'repetir', u'to repeat', u'repitiera', u'repitieras', u'repitiera', u'repitiéramos', u'repitierais', u'repitieran'],
[u'saber', u'to know; know how', u'supiera', u'supieras', u'supiera', u'supiéramos', u'supierais', u'supieran'],
[u'salir', u'to exit; leave', u'saliera', u'salieras', u'saliera', u'saliéramos', u'salierais', u'salieran'],
[u'seguir', u'to follow', u'siguiera', u'siguieras', u'siguiera', u'siguiéramos', u'siguierais', u'siguieran'],
[u'sentir', u'to feel', u'sintiera', u'sintieras', u'sintiera', u'sintiéramos', u'sintierais', u'sintieran'],
[u'ser', u'to be (descriptive)', u'fuera', u'fueras', u'fuera', u'fuéramos', u'fuerais', u'fueran'],
[u'servir', u'to serve', u'sirviera', u'sirvieras', u'sirviera', u'sirviéramos', u'sirvierais', u'sirvieran'],
[u'tener', u'to have; own; keep', u'tuviera', u'tuvieras', u'tuviera', u'tuviéramos', u'tuvierais', u'tuvieran'],
[u'traer', u'to bring; fetch', u'trajera', u'trajeras', u'trajera', u'trajéramos', u'trajerais', u'trajeran'],
[u'venir', u'to come', u'viniera', u'vinieras', u'viniera', u'viniéramos', u'vinierais', u'vinieran'],
[u'ver', u'to see; view; look; consider', u'cupiera', u'cupieras', u'cupiera', u'cupiéramos', u'cupierais', u'cupieran'],
[u'volar', u'to fly', u'volara', u'volaras', u'volara', u'voláramos', u'volarais', u'volaran'],
[u'volver', u'to return; go back', u'volviera', u'volvieras', u'volviera', u'volviéramos', u'volvierais', u'volvieran']
]

# ********** Conditional Tense ************
conditional_tense = [
[u'hablar', u'to speak; talk', u'hablaría', u'hablarías', u'hablaría', u'hablaríamos', u'hablaríais', u'hablarían'],
[u'comer', u'to eat; feed', u'comería', u'comerías', u'comería', u'comeríamos', u'comeríais', u'comerían'],
[u'escrebir', u'to write', u'escrebiría', u'escrebirías', u'escrebiría', u'escrebiríamos', u'escrebiríais', u'escrebirían'],
[u'pagar', u'to pay', u'pagaría', u'pagarías', u'pagaría', u'pagaríamos', u'pagaríais', u'pagarían'],
[u'tocar', u'to touch; play an instrument', u'tocaría', u'tocarías', u'tocaría', u'tocaríamos', u'tocaríais', u'tocarían'],
[u'almorzar', u'to (have) lunch', u'almorzaría', u'almorzarías', u'almorzaría', u'almorzaríamos', u'almorzaríais', u'almorzarían'],
[u'caer', u'to fall; drop', u'caería', u'caerías', u'caería', u'caeríamos', u'caeríais', u'caerían'],
[u'cerrar', u'to close; shut', u'cerraría', u'cerrarías', u'cerraría', u'cerraríamos', u'cerraríais', u'cerrarían'],
[u'comenzar', u'to begin; start', u'comenzaría', u'comenzarías', u'comenzaría', u'comenzaríamos', u'comenzaríais', u'comenzarían'],
[u'conocer', u'to be familiar', u'conocería', u'conocerías', u'conocería', u'conoceríamos', u'conoceríais', u'conocerían'],
[u'conseguir', u'to get', u'conseguiría', u'conseguirías', u'conseguiría', u'conseguiríamos', u'conseguiríais', u'conseguirían'],
[u'contar', u'to count; tell', u'contaría', u'contarías', u'contaría', u'contaríamos', u'contaríais', u'contarían'],
[u'dar', u'to give', u'daría', u'darías', u'daría', u'daríamos', u'daríais', u'darían'],
[u'decir', u'to say; tell', u'diría', u'dirías', u'diría', u'diríamos', u'diríais', u'dirían'],
[u'defender', u'to defend', u'defendería', u'defenderías', u'defendería', u'defenderíamos', u'defenderíais', u'defenderían'],
[u'dormir', u'to sleep', u'dormiría', u'dormirías', u'dormiría', u'dormiríamos', u'dormiríais', u'dormirían'],
[u'empezar', u'to begin; start', u'empezaría', u'empezarías', u'empezaría', u'empezaríamos', u'empezaríais', u'empezarían'],
[u'encontrar', u'to find; meet', u'encontraría', u'encontrarías', u'encontraría', u'encontraríamos', u'encontraríais', u'encontrarían'],
[u'entender', u'to understand', u'entendería', u'entenderías', u'entendería', u'entenderíamos', u'entenderíais', u'entenderían'],
[u'estar', u'to be (temporary)', u'estaría', u'estarías', u'estaría', u'estaríamos', u'estaríais', u'estarían'],
[u'haber', u'to have; to credit', u'habría', u'habrías', u'habría', u'habríamos', u'habríais', u'habrían'],
[u'hacer', u'to do; make; perform', u'haría', u'harías', u'haría', u'haríamos', u'haríais', u'harían'],
[u'ir', u'to go', u'iría', u'irías', u'iría', u'iríamos', u'iríais', u'irían'],
[u'jugar', u'to play', u'jugaría', u'jugarías', u'jugaría', u'jugaríamos', u'jugaríais', u'jugarían'],
[u'llover', u'to rain', u'llovería', u'lloverías', u'llovería', u'lloveríamos', u'lloveríais', u'lloverían'],
[u'mostrar', u'to show', u'mostraría', u'mostrarías', u'mostraría', u'mostraríamos', u'mostraríais', u'mostrarían'],
[u'mover', u'to move', u'movería', u'moverías', u'movería', u'moveríamos', u'moveríais', u'moverían'],
[u'nevar', u'to snow', u'nevaría', u'nevarías', u'nevaría', u'nevaríamos', u'nevaríais', u'nevarían'],
[u'oir', u'to hear', u'oiría', u'oirías', u'oiría', u'oiríamos', u'oiríais', u'oirían'],
[u'pedir', u'to book; order; ask; reserve', u'pediría', u'pedirías', u'pediría', u'pediríamos', u'pediríais', u'pedirían'],
[u'pensar', u'to think', u'pensaría', u'pensarías', u'pensaría', u'pensaríamos', u'pensaríais', u'pensarían'],
[u'perder', u'to lose; miss', u'perdería', u'perderías', u'perdería', u'perderíamos', u'perderíais', u'perderían'],
[u'poder', u'to be able; can; may', u'podría', u'podrías', u'podría', u'podríamos', u'podríais', u'podrían'],
[u'poner', u'to put; put on; lay; send', u'pondría', u'pondrías', u'pondría', u'pondríamos', u'pondríais', u'pondrían'],
[u'querer', u'to want; wish; like', u'querría', u'querrías', u'querría', u'querríamos', u'querríais', u'querrían'],
[u'recordar', u'to remember; remind', u'recordaría', u'recordarías', u'recordaría', u'recordaríamos', u'recordaríais', u'recordarían'],
[u'repetir', u'to repeat', u'repetiría', u'repetirías', u'repetiría', u'repetiríamos', u'repetiríais', u'repetirían'],
[u'saber', u'to know; know how', u'sabría', u'sabrías', u'sabría', u'sabríamos', u'sabríais', u'sabrían'],
[u'salir', u'to exit; leave', u'saldría', u'saldrías', u'saldría', u'saldríamos', u'saldríais', u'saldrían'],
[u'seguir', u'to follow', u'seguiría', u'seguirías', u'seguiría', u'seguiríamos', u'seguiríais', u'seguirían'],
[u'sentir', u'to feel', u'sentiría', u'sentirías', u'sentiría', u'sentiríamos', u'sentiríais', u'sentirían'],
[u'ser', u'to be (descriptive)', u'sería', u'serías', u'sería', u'seríamos', u'seríais', u'serían'],
[u'servir', u'to serve', u'serviría', u'servirías', u'serviría', u'serviríamos', u'serviríais', u'servirían'],
[u'tener', u'to have; own; keep', u'tendría', u'tendrías', u'tendría', u'tendríamos', u'tendríais', u'tendrían'],
[u'traer', u'to bring; fetch', u'traería', u'traerías', u'traería', u'traeríamos', u'traeríais', u'traerían'],
[u'venir', u'to come', u'vendría', u'vendrías', u'vendría', u'vendríamos', u'vendríais', u'vendrían'],
[u'ver', u'to see; view; look; consider', u'vería', u'verías', u'vería', u'veríamos', u'veríais', u'verían'],
[u'volar', u'to fly', u'volaría', u'volarías', u'volaría', u'volaríamos', u'volaríais', u'volarían'],
[u'volver', u'to return; go back', u'volvería', u'volverías', u'volvería', u'volveríamos', u'volveríais', u'volverían']
]

# ********** Imperative Tense ************
imperative_tense = [
[u'hablar', u'to speak; talk', u'habla'],
[u'comer', u'to eat; feed',  u'come'],
[u'escrebir', u'to write',  u'escrebe'],
[u'pagar', u'to pay', u'paga'],
[u'tocar', u'to touch; play an instrument', u'toca'],
[u'almorzar', u'to (have) lunch',  u'almuerza'],
[u'caer', u'to fall; drop', u'cae'],
[u'cerrar', u'to close; shut',  u'cierra'],
[u'comenzar', u'to begin; start',  u'comienza'],
[u'conocer', u'to be familiar',  u'conoce'],
[u'conseguir', u'to get', u'consigue'],
[u'contar', u'to count; tell', u'cuenta'],
[u'dar', u'to give', u'da'],
[u'decir', u'to say; tell', u'di'],
[u'defender', u'to defend', u'defiende'],
[u'dormir', u'to sleep', u'duerme'],
[u'empezar', u'to begin; start', u'empieza'],
[u'encontrar', u'to find; meet', u'encuentra'],
[u'entender', u'to understand', u'entiende'],
[u'estar', u'to be (temporary)', u'está'],
[u'haber', u'to have; to credit', u'habe'],
[u'hacer', u'to do; make; perform', u'haz'],
[u'ir', u'to go', u've'],
[u'jugar', u'to play', u'juega'],
[u'llover', u'to rain', u'llueve'],
[u'mostrar', u'to show', u'muestra'],
[u'mover', u'to move', u'mueve'],
[u'nevar', u'to snow', u'nieva'],
[u'oir', u'to hear', u'oye'],
[u'pedir', u'to book; order; ask; reserve', u'pide'],
[u'pensar', u'to think', u'piensa'],
[u'perder', u'to lose; miss', u'pierde'],
[u'poder', u'to be able; can; may', u'puede'],
[u'poner', u'to put; put on; lay; send', u'pon'],
[u'querer', u'to want; wish; like', u'quiere'],
[u'recordar', u'to remember; remind', u'recuerda'],
[u'repetir', u'to repeat', u'repite'],
[u'saber', u'to know; know how', u'sabe'],
[u'salir', u'to exit; leave', u'sal'],
[u'seguir', u'to follow', u'sigue'],
[u'sentir', u'to feel', u'siente'],
[u'ser', u'to be (descriptive)', u'sé'],
[u'servir', u'to serve', u'sirve'],
[u'tener', u'to have; own; keep', u'ten'],
[u'traer', u'to bring; fetch', u'trae'],
[u'venir', u'to come', u'ven'],
[u'ver', u'to see; view; look; consider', u've'],
[u'volar', u'to fly', u'vuela'],
[u'volver', u'to return; go back', u'vuelve']
]

# ********** Gerund ************
gerund = [
[u'hablar', u'to speak; talk', u'hablando'],
[u'comer', u'to eat; feed', u'comiendo'],
[u'escrebir', u'to write', u'escrebiendo'],
[u'pagar', u'to pay', u'pagando'],
[u'tocar', u'to touch; play an instrument', u'tocando'],
[u'almorzar', u'to (have) lunch', u'almorzando'],
[u'caer', u'to fall; drop', u'cayendo'],
[u'cerrar', u'to close; shut', u'cerrando'],
[u'comenzar', u'to begin; start', u'comenzando'],
[u'conocer', u'to be familiar', u'conociendo'],
[u'conseguir', u'to get', u'consiguiendo'],
[u'contar', u'to count; tell', u'contando'],
[u'dar', u'to give', u'dando'],
[u'decir', u'to say; tell', u'diciendo'],
[u'defender', u'to defend', u'defendiendo'],
[u'dormir', u'to sleep', u'durmiendo'],
[u'empezar', u'to begin; start', u'empezando'],
[u'encontrar', u'to find; meet', u'encontrando'],
[u'entender', u'to understand', u'entendiendo'],
[u'estar', u'to be (temporary)', u'estando'],
[u'haber', u'to have; to credit', u'habiendo'],
[u'hacer', u'to do; make; perform', u'haciendo'],
[u'ir', u'to go', u'yendo'],
[u'jugar', u'to play', u'jugando'],
[u'llover', u'to rain', u'lloviendo'],
[u'mostrar', u'to show', u'mostrando'],
[u'mover', u'to move', u'moviendo'],
[u'nevar', u'to snow', u'nevando'],
[u'oir', u'to hear', u'oyendo'],
[u'pedir', u'to book; order; ask; reserve', u'pidiendo'],
[u'pensar', u'to think', u'pensando'],
[u'perder', u'to lose; miss', u'perdiendo'],
[u'poder', u'to be able; can; may', u'pudiendo'],
[u'poner', u'to put; put on; lay; send', u'poniendo'],
[u'querer', u'to want; wish; like', u'queriendo'],
[u'recordar', u'to remember; remind', u'recordando'],
[u'repetir', u'to repeat', u'repitiendo'],
[u'saber', u'to know; know how', u'sabiendo'],
[u'salir', u'to exit; leave', u'saliendo'],
[u'seguir', u'to follow', u'siguiendo'],
[u'sentir', u'to feel', u'sintiendo'],
[u'ser', u'to be (descriptive)', u'siendo'],
[u'servir', u'to serve', u'sirviendo'],
[u'tener', u'to have; own; keep', u'teniendo'],
[u'traer', u'to bring; fetch', u'trayendo'],
[u'venir', u'to come', u'viniendo'],
[u'ver', u'to see; view; look; consider', u'viendo'],
[u'volar', u'to fly', u'volando'],
[u'volver', u'to return; go back', u'volviendo']
]

# ********** Past Participle ************
past_participle = [
[u'hablar', u'to speak; talk', u'hablado'],
[u'comer', u'to eat; feed', u'comido'],
[u'escrebir', u'to write', u'escrito'],
[u'pagar', u'to pay', u'pagado'],
[u'tocar', u'to touch; play an instrument', u'tocado'],
[u'almorzar', u'to (have) lunch', u'almorzado'],
[u'caer', u'to fall; drop', u'caído'],
[u'cerrar', u'to close; shut', u'cerrado'],
[u'comenzar', u'to begin; start', u'comenzado'],
[u'conocer', u'to be familiar', u'conocido'],
[u'conseguir', u'to get', u'conseguido'],
[u'contar', u'to count; tell', u'contado'],
[u'dar', u'to give', u'dado'],
[u'decir', u'to say; tell', u'dicho'],
[u'defender', u'to defend', u'defendido'],
[u'dormir', u'to sleep', u'dormido'],
[u'empezar', u'to begin; start', u'empezado'],
[u'encontrar', u'to find; meet', u'encontrado'],
[u'entender', u'to understand', u'entendido'],
[u'estar', u'to be (temporary)', u'estado'],
[u'haber', u'to have; to credit', u'habido'],
[u'hacer', u'to do; make; perform', u'hecho'],
[u'ir', u'to go', u'ido'],
[u'jugar', u'to play', u'jugado'],
[u'llover', u'to rain', u'llovido'],
[u'mostrar', u'to show', u'mostrado'],
[u'mover', u'to move', u'movido'],
[u'nevar', u'to snow', u'nevado'],
[u'oir', u'to hear', u'oído'],
[u'pedir', u'to book; order; ask; reserve', u'pedido'],
[u'pensar', u'to think', u'pensado'],
[u'perder', u'to lose; miss', u'perdido'],
[u'poder', u'to be able; can; may', u'podido'],
[u'poner', u'to put; put on; lay; send', u'puesto'],
[u'querer', u'to want; wish; like', u'querido'],
[u'recordar', u'to remember; remind', u'recordado'],
[u'repetir', u'to repeat', u'repetido'],
[u'saber', u'to know; know how', u'sabido'],
[u'salir', u'to exit; leave', u'salido'],
[u'seguir', u'to follow', u'seguido'],
[u'sentir', u'to feel', u'sentido'],
[u'ser', u'to be (descriptive)', u'sido'],
[u'servir', u'to serve', u'servido'],
[u'tener', u'to have; own; keep', u'tenido'],
[u'traer', u'to bring; fetch', u'traído'],
[u'venir', u'to come', u'venido'],
[u'ver', u'to see; view; look; consider', u'visto'],
[u'volar', u'to fly', u'volado'],
[u'volver', u'to return; go back', u'vuelto']
]
